### ISSUE TITLE
Ray casting

### ISSUE THREAD

**Issue by rpopovici** [kip-hart/AABBTree#11]
Hello, 

I have some questions:
- Is this implementation able to detect polygon intersection? 
- Is ray casting supported?

Thanks

**Comment by kip-hart** [comment]
Hi, this package does not support either of those. The two classes in the package, AABB and AABBTree, only consider bounding boxes.

Since the bounding boxes of two objects overlap whenever the objects themselves overlap, the AABBTree can be used to quickly identify which objects to check for overlap.

I don't have a recommendation for ray tracing, unfortunately, other than to search PyPI for a supporting package.

**Comment by kip-hart** [comment]
Closing this as a week has passed. Feel free to re-open if you have any followup questions.
