### ISSUE TITLE
Overlap between trees

### ISSUE THREAD

**Issue by gstfrr** [kip-hart/AABBTree#7]
Hi. I'm working in a project and I need to verify if two irregular (nonconvex) meshes are overlapping or not. I create an python function that subdivide the mesh in boxes and I add those boxes to the tree. I do this for both meshes. My question is: There is a way to verify overlap between two trees? 

![image](https://user-images.githubusercontent.com/20268946/91010927-c5e43800-e5b9-11ea-9458-f37d147f3599.png)

**Comment by kip-hart** [comment]
Hi thank you for your inquiry. At this time, there's only testing for overlap between an box and a tree, not two trees. Do you have any suggestions for an algorithm?

I think something similar to the box and tree would work. A BFS approach could be one where the code would first check if the root nodes overlap, then if they do split both root nodes into their left and right branches and check again, splitting the trees until it get down to checking if two boxes overlap.

I don't mind adding tree-to-tree overlap to the code - let me know what you think.

**Comment by kip-hart** [comment]
I have added overlap checking for trees and released a new version (v2.6.0).  In the `does_overlap`, `overlap_aabbs`,  and `overlap_values` methods you can input another tree, rather than another box.

For example, `tree1.does_overlap(tree2)` would return True if any of the boxes in `tree1` overlap with the boxes in `tree2`.

I would try both `tree1.does_overlap(tree2, method='DFS')` and `tree1.does_overlap(tree2, method='BFS')` to see which search pattern is faster for your application.

Thank you again for reaching out. Please feel free to reopen if there are any issues.
